Web/MVC/MusicSchool/MusicSchool/Models/Tutor.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MusicSchool.Models
{
    public class Tutor
    {
        public int TutorID { get; set; }
        public String FirstName { get; set; }
        public String LastName { get; set; }
        public int PhoneNumber { get; set; }
        public virtual Instrument Instrument { get; set; }
        public virtual List<InstrumentQualification> InstrumentQualifications { get; set; }
        public virtual List<Student> Students { get; set; }
    }
}

Web/MVC/MusicSchool/MusicSchool/Controllers/SchoolController.cs
using MusicSchool.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MusicSchool.Controllers
{
    public class SchoolController : Controller
    {
        private MusicSchoolDbContext MusicSchoolDB = new MusicSchoolDbContext();

        [HttpGet]
        public ActionResult Enrolment()
        {
            IEnumerable<Student> students = MusicSchoolDB.Students.ToList(); // gets a list of students
            InstrumentsDropDownBox();
            return View(students);
        }

        [HttpPost]
        public ActionResult Enrolment(FormCollection formCollection)
        {
            int newInstrument = Convert.ToInt32(formCollection["AllInstrumentsDD"]); // gets the id from the instruments drop down box
            int studentsid = Convert.ToInt32(formCollection["StudentsDD"]); // gets the id from the instruments drop down box
            Student newInstrumentChosen = new Student() { StudentID = studentsid, InstrumentID = newInstrument };

            MusicSchoolDB.Students.Attach(newInstrumentChosen);
            MusicSchoolDB.Entry(newInstrumentChosen).Property(x => x.InstrumentID).IsModified = true;
            MusicSchoolDB.SaveChanges();
            
            IEnumerable<Student> students = MusicSchoolDB.Students.ToList(); // gets a list of students
            return RedirectToAction("Enrolment", students);
        }

        /* Page that shows all the students with their respective tutors */
        public ActionResult Classes()
        {
            IEnumerable<Tutor> allTutors = MusicSchoolDB.Tutors.ToList();
            return View("Classes", allTutors);
        }

        /* Assigning students to a particular tutor */
        public ActionResult AssignTutors()
        {
            int chosenTutor = 0;
            IEnumerable<Student> allStudents = MusicSchoolDB.Students.ToList(); // Get a list of students
            IEnumerable<InstrumentQualification> allQualifications = MusicSchoolDB.InstrumentQualifications.ToList(); // Get a list of qualifications
            foreach (Student s in allStudents) // Go through the list of students
            {                
                foreach (InstrumentQualification iq in allQualifications)
                {
                    if (s.InstrumentID == iq.InstrumentID) // Checks whether the students instrument is the same as the tutors instrument
                    {
                        if (iq.Level >= 6) // Tutor level must be at least 6 in order to teach the instrument
                        {
                            if (s.Age >= 16)
                            {
                                if (iq.Level >= 8)
                                {
                                    chosenTutor = iq.TutorID; // Assigns tutor id if the students is older than 16 and the tutor has a good enough level 
                                }
                            }
                            else
                            {
                                chosenTutor = iq.TutorID; // Assigns tutor id to a regular student
                            }
                        }
                    }
                }
                /* Adds the tutor id into the database for students */
                Student newTutor = new Student() { StudentID = s.StudentID, TutorID = chosenTutor };
                using (MusicSchoolDbContext db = new MusicSchoolDbContext())
                {
                    db.Students.Attach(newTutor);
                    db.Entry(newTutor).Property(x => x.TutorID).IsModified = true;
                    db.SaveChanges();
                }                
            }
            return View();
        }

        public void InstrumentsDropDownBox()
        {
            IEnumerable<Instrument> Instruments = MusicSchoolDB.Instruments.ToList();
            List<SelectListItem> instruments = new List<SelectListItem>();
            foreach (Instrument i in Instruments)
            {
                instruments.Add(new SelectListItem { Text = i.Name, Value = i.InstrumentID.ToString() });
            }
            ViewBag.AllInstrumentsDD = instruments;
        }
	}
}

Web/MVC/MusicSchool/MusicSchool/Controllers/StudentController.cs
using MusicSchool.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MusicSchool.Controllers
{
    public class StudentController : Controller
    {
        private MusicSchoolDbContext MusicSchoolDB = new MusicSchoolDbContext();
        // GET: /Student/
        [HttpGet]
        public ActionResult ShowStudents()
        {
            IEnumerable<Student> students = MusicSchoolDB.Students.ToList(); // gets a list of students
            StudentDropDownBox();
            InstrumentsDropDownBox();
            return View(students);
        }
        
        [HttpPost]
        public ActionResult ShowStudents(FormCollection formCollection)
        {
            IEnumerable<Student> allStudents = MusicSchoolDB.Students.ToList();
            IEnumerable<Student> newStudent = new List<Student>();

            /* Add a Student */
            Student student = new Student();
            if ((formCollection["firstName"] != "") && (formCollection["LastName"] != "") && (formCollection["PhoneNumber"] != "") && (formCollection["Age"] != "")) // Checks whether the any of the fields are not empty
            {
                student.FirstName = formCollection["firstName"]; // get text from the 'firstName' text box
                student.LastName = formCollection["lastName"]; // get text from the 'lastName' text box
                student.PhoneNumber = Convert.ToInt32(formCollection["PhoneNumber"]); // get text from the 'PhoneNumber' text box
                student.Age = Convert.ToInt32(formCollection["Age"]); // get text from the 'Age' text box
                student.InstrumentID = Convert.ToInt32(formCollection["AllInstrumentsDD"]); // gets the id from the instruments drop down box
                student.OwnInstrument = Boolean.Parse(formCollection["OwnInstrumentDD"]); // gets the boolean value from the drop down box for whether a student owns an instrument

                MusicSchoolDB.Students.Add(student);
                MusicSchoolDB.SaveChanges();
            }


            /* Student Details */
            int studentID = Convert.ToInt32(formCollection["AllStudentsDD"]);
            Student DisplayStudent = new Student();
            foreach (Student s in allStudents)
            {
                if (s.StudentID == studentID)
                {
                    DisplayStudent.StudentID = studentID;
                    DisplayStudent.FirstName = s.FirstName;
                    DisplayStudent.LastName = s.LastName;
                    DisplayStudent.PhoneNumber = s.PhoneNumber;
                    DisplayStudent.Age = s.Age;
                    DisplayStudent.Instrument.Name = s.Instrument.Name;
                    DisplayStudent.OwnInstrument = s.OwnInstrument;
                }
            }

            IEnumerable<Student> students = MusicSchoolDB.Students.ToList(); // gets a list of students

            return RedirectToAction("ShowStudents", students);
        }

        /*************************************************************************************************************************************************************
                                                DROP DOWN BOXES 
        * ***********************************************************************************************************************************************************
        */

        public void StudentDropDownBox()
        {
            IEnumerable<Student> allStudents = MusicSchoolDB.Students.ToList();
            List<SelectListItem> students = new List<SelectListItem>();
            foreach (Student s in allStudents)
            {
                students.Add(new SelectListItem { Text = s.FirstName + " " + s.LastName, Value = s.StudentID.ToString() });
            }
            ViewBag.AllStudentsDD = students;
        }

        public void InstrumentsDropDownBox()
        {
            IEnumerable<Instrument> Instruments = MusicSchoolDB.Instruments.ToList();
            List<SelectListItem> instruments = new List<SelectListItem>();
            foreach (Instrument i in Instruments)
            {
                instruments.Add(new SelectListItem { Text = i.Name, Value = i.InstrumentID.ToString() });
            }
            ViewBag.AllInstrumentsDD = instruments;
        }

        /* Page that shows all the details for one student */
        public ActionResult Details(int studentID)
        {
            Student current = MusicSchoolDB.Students.Find(studentID); // finds one student and passes it to the view
            return View("Details", current);
        }
	}
}

Web/MVC/MusicSchool/MusicSchool/Controllers/TutorController.cs
using MusicSchool.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MusicSchool.Controllers
{
    public class TutorController : Controller
    {
        private MusicSchoolDbContext MusicSchoolDB = new MusicSchoolDbContext();
        [HttpGet]
        public ActionResult ShowTutors()
        {
            IEnumerable<Tutor> allTutors = MusicSchoolDB.Tutors.ToList();
            InstrumentsDropDownBox();
            return View(allTutors);
        }
        [HttpPost]
        public ActionResult ShowTutors(FormCollection formCollection, string submit)
        {
            IEnumerable<Tutor> tutors = MusicSchoolDB.Tutors.ToList(); // gets a list of students
            try
            {
                switch (submit) // checks which button is clicked
                {
                    case "Save": // adding a tutor
                        Tutor tutor = new Tutor();
                        tutor.FirstName = formCollection["firstName"];
                        tutor.LastName = formCollection["lastName"];
                        tutor.PhoneNumber = Convert.ToInt32(formCollection["PhoneNumber"]);
                        MusicSchoolDB.Tutors.Add(tutor);
                        MusicSchoolDB.SaveChanges();
                        break;
                    case "Update Tutor": // adding a qualification for a particular tutor

                        int tutorIDUpdate = Convert.ToInt32(formCollection["TutorsDD"]);
                        int InstrumentUpdate = Convert.ToInt32(formCollection["AllInstrumentsDD"]);
                        int LevelUpdate = Convert.ToInt32(formCollection["LevelDD"]);
                        InstrumentQualification newQualification = new InstrumentQualification() { TutorID = tutorIDUpdate, InstrumentID = InstrumentUpdate, Level = LevelUpdate };
                        MusicSchoolDB.InstrumentQualifications.Add(newQualification);
                        MusicSchoolDB.SaveChanges();
                        break;
                }
            }
            catch (Exception e)
            {
                Debug.WriteLine(e.Message);
            }

            return RedirectToAction("ShowTutors", tutors);
        }

        /* Creates a drop down box for instruments*/
        public void InstrumentsDropDownBox()
        {
            IEnumerable<Instrument> Instruments = MusicSchoolDB.Instruments.ToList();
            List<SelectListItem> instruments = new List<SelectListItem>();
            foreach (Instrument i in Instruments)
            {
                instruments.Add(new SelectListItem { Text = i.Name, Value = i.InstrumentID.ToString() });
            }
            ViewBag.AllInstrumentsDD = instruments;
        }
	}
}

Web/MVC/MusicSchool/MusicSchool/Views/Tutor/ShowTutors.cshtml
@model List<MusicSchool.Models.Tutor>

@{
    Layout = null;
}
<!--
    Lachie Rutherford
    I do not have permission for all images that are used
-->

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width">

    <title> BIT Music School </title>

    <link href="@Url.Content("~/MusicSchoolSS.css")" rel="stylesheet" type="text/css" />

</head>
<body>


    <div class="page">
        <div class="header">

            <img id="img_Banner" alt="Banner" src="@Url.Content("~/Music.jpg")" width="900" />

        </div>
        <div class="logo"></div>
        <div class="navigation">
            <ul>
                <li>@Html.ActionLink("Home", "Home", "Home")</li>
                <li>@Html.ActionLink("Students", "ShowStudents", "Student")</li>
                <li>@Html.ActionLink("Tutors", "ShowTutors", "Tutor")</li>
                <li>@Html.ActionLink("Enrolment", "Enrolment", "School")</li>
            </ul>
        </div>

        <div class="title">
            <h2>  Tutors </h2>
        </div>

        <div class="text">

            <table>
                <tr>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Phone Number</th>
                    <th>Qualification</th>
                </tr>

                @foreach (MusicSchool.Models.Tutor t in Model)
                {
                    <tr>
                        <td> @t.FirstName</td>
                        <td> @t.LastName</td>
                        <td> @t.PhoneNumber</td>
                        <td>
                            @foreach (MusicSchool.Models.InstrumentQualification qualifications in t.InstrumentQualifications)
                            {
                                <p>Instrument: @qualifications.Instrument.Name, Level: @qualifications.Level</p>
                            }
                        </td>
                    </tr>
                }

            </table>

            <h3>Add a Tutor</h3>

            @using (Html.BeginForm("ShowTutors", "Tutor"))
            {
                <table>
                    <tr>
                        <td>
                            @Html.Label("First Name")
                        </td>
                        <td>
                            @Html.TextBox("firstName")
                        </td>
                    </tr>
                    <tr>
                        <td>
                            @Html.Label("Last Name")
                        </td>
                        <td>
                            @Html.TextBox("lastName")
                        </td>
                    </tr>
                    <tr>
                        <td>
                            @Html.Label("Phone Number")
                        </td>
                        <td>
                            <input type="number" name="PhoneNumber" id="PhoneNumber" />
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <input type="submit" name="submit" value="Save" />
                        </td>
                    </tr>
                </table>
                <br />
                <h3>Update the Qualification of a Tutor</h3>
                <table>
                    <tr>
                        <td>
                            @Html.Label("Choose a Tutor")
                        </td>
                        <td>
                            <select name="TutorsDD">
                                @foreach (var tutors in Model)
                                {
                                    <option value="@tutors.TutorID">@tutors.FirstName @tutors.LastName</option>
                                }
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            @Html.Label("Instrument")
                        </td>
                        <td>
                            @Html.DropDownList("AllInstrumentsDD")
                        </td>
                    </tr>
                    <tr>
                        <td>
                            @Html.Label("Level")
                        </td>
                        <td>
                            <select name="LevelDD">
                                @for (int i = 1; i <= 9; i++)
                                {
                                    <option value="@i">@i</option>
                                }
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <input type="submit" name="submit" value="Update Tutor" />
                        </td>
                    </tr>
                </table>
            }

        </div>
    </div>
</body>
</html>